### ISSUE TITLE
Anno 2205 crash after repack rda file

### ISSUE THREAD

**Issue by Kamillio** [lysannschlegel/RDAExplorer#6] opened 2017-05-23 10:36 UTC
Hi,
I have read all closed issues but cannot find anything to help me.
Maybe I'm doing something wrong but when open and save a rda file data12.rda (RDAExplorer 1.3) and copy back to game folder, game freeze while loading. I generated a new file.db by the FileDBGenerator but with the same result. I thing something wrong is with the FileDBGenerator.

1) File db generator does not see all rda files and new filesize of the file.db is smaller then the original file.db. These files are not visible in the file db generator window:

- English(US)0.rda
- English(US)1.rda
- English(US)2.rda
- English(US)3.rda
- English(US)4.rda
- English(US)5.rda
- English(US)6.rda
- English(US)7.rda
- English(US)8.rda
- English(US)9.rda
Other files data0.rda - data18.rda are visible OK. Therefore is file.db probably invalid.

2) When I save a rda file must compression be checked? And which items of compression should by checked? I want to make language localization but I cannot change the data. I tried to change PreferLocalFiles to True in engine.ini and copy extracted files to maindata but it does not work.

My game version is 1.8 I thing (Anno2205.exe version info is 1.8.3726.17139). Maybe file format has changed due to update?

Please, can you investigate and let me know what is wrong?

**Comment by lysanntranvouez** [comment] 2017-05-25 14:39
Thanks for the detailed report. I haven't tested this with newer versions of the game for a while, so an update might very well be the cause of your troubles.

I'm hoping to find some time this weekend to investigate and hopefully fix it.

**Comment by lysanntranvouez** [comment] 2017-05-28 14:09
Alright, so I updated my Anno and made a few tests. There are a couple of points here:

I do not think that the English(US) files are required to be listed in file.db. I might be wrong about this, but it's interesting to note that the original file.db mentions different languages than I can download in my Uplay launcher.

I tried just generating a new file.db, without modifying any rda files and then launched the game. This did not crash for me.
But I ended up with a broken looking game, so something is definitely wrong.

But can you please try the exact same thing? Restore all the original files via Uplay, make sure the game works in that state. Then generate a new file.db (making sure only original rda files are selected), and let me know the results? Would be interesting to know.

It could well be of course that what generates a broken looking game for me might make it crash on your system, so I'm not holding my breath.

**Comment by Kamillio** [comment] 2017-05-29 12:09
Thank you for reply. I also made a few tests:

I restored files via Uplay and the game worked correctly. I copied all rda files to my backup folder and from this folder I generated a new file.db. I replaced the original file.db and game crash before loading (black screen and end).
When I was generating a file.db from original maindata folder and replaced original file.db and lunch the game, game crash after showing "Loading" text. But I found a solution for this state: In filesystem location \users\_username_\Documents\Anno 2205\fx\temp are probably temporary verification files. When I clean up this temp folder, game is lunched corectly but when I start a mission I get probably the same broken looking game (only blue background) result you mentioned.

Note: I found out when I renamed my "backup" folder to "maindata" and generate from here game is lunched as in the previous case but with broken looking. It seems important to have the folder named as the "maindata".

What's strange: file size of a new genrated file.db is 70.4 MB but original file.db file size is 79.1 MB. Filesize difference is more than 8 MB. So I think there is something wrong in rda file reading process.

In your src of the project is FileDBTool but not compiled to binary. I wanted make a dump for diferencies but I wasn't able to open the soloution in Visual Studio 2017 (errors in open solution). I'm programmer but not in the .net. So can you build this tool as standalone application?

And I have a one question. If I modify content of a existing file in a rda archive (no add a new file, no delete existing, no rename existing - only change content) is it necessary to generate a new file.db?

**Comment by lysanntranvouez** [comment] 2017-05-29 15:57
> Note: I found out when I renamed my "backup" folder to "maindata" and generate from here game is lunched as in the previous case but with broken looking. It seems important to have the folder named as the "maindata".

Yes, that might be the case. A bit stupid, I think I could easily fix that.

> What's strange: file size of a new genrated file.db is 70.4 MB but original file.db file size is 79.1 MB. Filesize difference is more than 8 MB. So I think there is something wrong in rda file reading process.

My plan would be to check what is missing by making a binary diff between the original and the generated file.db. I had some trouble with that though, because the order in which data is generated is different, so it is hard to see what is actually different. That's something I need to fix in the generator,  I simply didn't have the time yet.
But somewhere in there must be the reason for our blue background.

> In your src of the project is FileDBTool but not compiled to binary. I wanted make a dump for diferencies but I wasn't able to open the soloution in Visual Studio 2017 (errors in open solution). I'm programmer but not in the .net. So can you build this tool as standalone application?

Yes, I can write up a summary how to set it up later.

> And I have a one question. If I modify content of a existing file in a rda archive (no add a new file, no delete existing, no rename existing - only change content) is it necessary to generate a new file.db?

Yes, since the order of the data in the rda file changes, as well as the length of the changed entries. file.db contains for each rda file and each file in those, where the data for that particular file begins and how long it is.
Though it would be better if we could get it to work with PreferLocalFiles, so you don't need to repack the rda files and file.db after each small change.

**Comment by lysanntranvouez** [comment] 2018-11-24 13:58
Closing for age

**Closed as completed by lysanntranvouez** 2018-11-24 13:58 UTC
Labels: bug, game CTD
